# Generated by Django 4.0.5 on 2022-06-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
